language: node_js
cache:
  directories:
  - .nvm
install: npm install gitbook-cli -g
before_script: gitbook install
script: gitbook build -o gitbook-output
deploy:
  provider: pages
  local-dir: gitbook-output
  skip-cleanup: true
  github-token: $GITHUB_API_TOKEN
  keep-history: true
  on:
    branch: master
