language: node_js
before_install:
  - curl -fLo /tmp/pandoc-2.10.1-1-amd64.deb https://github.com/jgm/pandoc/releases/download/2.10.1/pandoc-2.10.1-1-amd64.deb
  - sudo dpkg -i /tmp/pandoc-2.10.1-1-amd64.deb
script: bash build.sh
deploy:
  provider: pages
  local-dir: book
  skip-cleanup: true
  github-token: $GITHUB_API_TOKEN
  keep-history: true
  on:
    branch: master
